name: network-calculator
version: 1.0
summary: Network calculator
description: |
  Simple network calculator
parts:
  netcalc:
    plugin: cmake
    source: src

apps:
  network-calculator:
    command: netcalc