name: netcalc
version: '1.1'
summary: Network calculator
description: Simple network calculator
grade: devel
base: core18

parts:
  netcalc:
    plugin: cmake
    source: src
    build-packages:
      - cmake
      - make

apps:
  netcalc:
    command: netcalc