name: netcalc
version: '1.1'
summary: Simple network calculator
description: Simple network calculator
grade: devel
base: core18
license: GPL-2.0

parts:
  netcalc:
    plugin: cmake
    source: src
    build-packages:
      - cmake
      - make

apps:
  netcalc:
    command: netcalc