name: netcalc
version: '2.2.5'
summary: Simple network calculator
description: |
  Simple program that converts values from an IP address and subnet mask.
  Has the ability to fetch data from the interface.
grade: stable
base: core18
license: GPL-2.0

apps:
  netcalc:
    command: netcalc
    plugs:
      - network
      - network-bind

parts:
  netcalc:
    plugin: cmake
    source: .
    build-packages:
      - cmake
      - make