name: netcalc
version: '2.2.2'
summary: Simple network calculator
description: Simple network calculator
grade: stable
base: core18
license: GPL-2.0

parts:
  netcalc:
    plugin: cmake
    source: .
    build-packages:
      - cmake
      - make

apps:
  netcalc:
    command: netcalc
    plugs:
      - network
      - network-bind